#index:
#    path: /
#    controller: App\Controller\DefaultController::index

teacher_make_question:
    path: /teacher/make_question/{teacherId}
    controller: App\Controller\TeacherController::makeQuestion

teacher_edit_question:
    path: /teacher/edit_question/{teacherId}/{questionId}
    controller: App\Controller\TeacherController::editQuestion

teacher_delete_question:
    path: /teacher/delete_question/{questionId}
    controller: App\Controller\TeacherController::deleteQuestion
    methods: [DELETE]

teacher_main:
    path: /teacher/main/{teacherId}
    controller: App\Controller\TeacherController::teacherMain

teacher_make_exam:
    path: /teacher/make_exam/{teacherId}
    controller: App\Controller\TeacherController::makeExam

make_exam_selected:
    path: /teacher/make_exam/{teacherId}/make_exam_selected/{questionIds}/{examTitle}
    controller: App\Controller\TeacherController::makeExamSelected
    methods: [POST]

teacher_make_exam_random:
    path: /teacher/make_exam/random/{teacherId}
    controller: App\Controller\TeacherController::makeExamRandom

teacher_make_exam_random_selected:
    path: /teacher/make_exam/random/{teacherId}/{examTitle}/{numbers}/{category}
    controller: App\Controller\TeacherController::makeExamRandomSelected
    methods: [POST]

teacher_exam_publish_set:
    path: /teacher/exam/publish/{examId}/set
    controller: App\Controller\TeacherController::makeExamPublish
    methods: [POST]

exam_show:
    path: /exam/{examId}/student/{studentId}
    controller: App\Controller\Exam::examShow

exam_main:
    path: /student/exam/{studentId}
    controller: App\Controller\Exam::examMain

exam_result:
    path: /student/exam/{studentId}/examResult/{examId}/{questionIds}
    controller: App\Controller\Exam::examResult

test:
    path: /test
    controller: App\Controller\Test::dummyStudentMaker